version: '3.3'

services:
  db:
    image: mysql:8.0.15
    container_name: wordpress_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: kohli
      MYSQL_USER: virat
      MYSQL_PASSWORD: virat1818

  wordpress:
    image: wordpress:latest
    container_name: wordpress_app
    depends_on:
      - db
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: virat
      WORDPRESS_DB_PASSWORD: virat1818
      WORDPRESS_DB_NAME: kohli
    volumes:
      - wordpress_data:/var/www/html

volumes:
  db_data:
  wordpress_data:
